# Generated by Django 5.0.6 on 2026-07-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, help_text='Post kategoriyasi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(blank=True, help_text='Qisqa tavsif / description', null=True),
        ),
    ]
