# Generated by Django 5.0.6 on 2026-07-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, help_text='Xabar mavzusi', max_length=255, null=True),
        ),
    ]
